# Generated by Django 4.1.2 on 2022-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="model_practice4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_char_field3", models.CharField(max_length=100)),
                ("image_field", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
