# Generated by Django 4.1.2 on 2022-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0002_model_practice4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_practice4",
            name="image_field",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
