# Generated by Django 4.1.2 on 2022-11-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0004_alter_model_practice4_image_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_practice4",
            name="file_field",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="model_practice4",
            name="image_field",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
