# Generated by Django 4.1.2 on 2022-11-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0005_model_practice4_file_field_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="model_student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s_first_name", models.CharField(max_length=100)),
                ("s_last_name", models.CharField(max_length=100)),
                ("s_email", models.EmailField(max_length=100)),
                ("s_emp_password", models.CharField(max_length=100)),
            ],
        ),
    ]
