# Generated by Django 4.1.2 on 2022-11-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0006_model_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_student",
            name="s_email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="model_student_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sd_branch", models.CharField(max_length=100)),
                ("sd_age", models.IntegerField(max_length=100)),
                ("sd_contact", models.IntegerField(max_length=100)),
                ("sd_city", models.CharField(max_length=100)),
                (
                    "sd_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practice_app2.model_student",
                        to_field="s_email",
                    ),
                ),
            ],
        ),
    ]
