# Generated by Django 4.1.2 on 2022-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0008_alter_model_student_details_sd_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model_student_details",
            name="sd_contact",
            field=models.BigIntegerField(),
        ),
    ]
