# Generated by Django 4.1.2 on 2022-12-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0011_model_sd_delete_model_student_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="model_sc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sc_branch", models.CharField(max_length=100)),
                (
                    "sc_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="practice_app2.model_student",
                        to_field="s_email",
                    ),
                ),
            ],
        ),
    ]
