# Generated by Django 4.1.2 on 2022-12-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0012_model_sc"),
    ]

    operations = [
        migrations.CreateModel(
            name="model_movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("m_name", models.CharField(max_length=100)),
            ],
        ),
    ]
