# Generated by Django 4.1.2 on 2022-12-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0013_model_movies"),
    ]

    operations = [
        migrations.CreateModel(
            name="model_characters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_name", models.CharField(max_length=100)),
            ],
        ),
    ]
