# Generated by Django 4.1.2 on 2022-12-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app2", "0014_model_characters"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_characters",
            name="c_movie",
            field=models.ManyToManyField(to="practice_app2.model_movies"),
        ),
    ]
