# Generated by Django 4.1.2 on 2022-11-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="new_model", old_name="email_id", new_name="email",
        ),
    ]
