# Generated by Django 4.1.2 on 2022-11-23 17:02

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0002_rename_email_id_new_model_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="model_practice",
            fields=[
                (
                    "boolean_only",
                    models.BooleanField(default=True, verbose_name="boolean field"),
                ),
                ("boolean_multi", models.BooleanField()),
                (
                    "char_field",
                    models.CharField(
                        help_text="help text",
                        max_length=100,
                        unique=True,
                        verbose_name="character field",
                    ),
                ),
                ("date_field", models.DateField(default=django.utils.timezone.now)),
                ("decimal_field", models.DecimalField(decimal_places=2, max_digits=5)),
                ("email_field", models.EmailField(max_length=100)),
                ("file_field", models.FileField(blank=True, upload_to="uploads")),
                ("image_field", models.ImageField(blank=True, upload_to="uploads")),
                ("integer_field", models.IntegerField()),
                ("slug_field", models.SlugField(default=True)),
                ("text_field", models.TextField()),
                ("url_field", models.URLField(max_length=100)),
                ("uuid1", models.UUIDField(default=uuid.uuid4)),
                (
                    "uuid2",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("date_and_time", models.DateTimeField()),
                (
                    "choice_field",
                    models.CharField(
                        choices=[
                            ("one", "pune"),
                            ("two", "mumbai"),
                            ("three", "goa"),
                            ("four", "vengurla"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
