# Generated by Django 4.1.2 on 2022-11-24 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="model_practice_app",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char_name_field",
                    models.CharField(
                        help_text="help text",
                        max_length=100,
                        unique=True,
                        verbose_name="character field",
                    ),
                ),
                ("date_field", models.DateField(default=django.utils.timezone.now)),
                ("decimal_field", models.DecimalField(decimal_places=2, max_digits=5)),
                ("email_field", models.EmailField(max_length=100)),
            ],
        ),
    ]
