# Generated by Django 4.1.2 on 2022-11-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model_practice_app",
            name="boolean_only",
            field=models.BooleanField(default=True, verbose_name="boolean field"),
        ),
    ]
