# Generated by Django 4.1.2 on 2022-11-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice_app", "0002_model_practice_app_boolean_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="model_practice2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_name_field2", models.CharField(max_length=100)),
                ("integer_field", models.IntegerField()),
                ("slug_field", models.SlugField(default=True)),
                ("text_field", models.TextField()),
                ("url_field", models.URLField(max_length=100)),
                (
                    "choice_field",
                    models.CharField(
                        choices=[
                            ("one", "pune"),
                            ("two", "mumbai"),
                            ("three", "goa"),
                            ("four", "vengurla"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
